### ISSUE TITLE
[Content]: Call to arts/code/whatever

### ISSUE THREAD

**Issue by Zughy** [minetest/blog#120]
### Blog Section

No idea

### Please enter your content.

I'd be nice to push people to contribute to Minetest. We definitely need developers (1000+ issues), designers and illustrators (main menu, website), promoters (ruben is the only one behind all the socials). We could provide some good first issue to start from and the like

**Comment by MisterE123** [comment]
I need specifics. If I just put out a general call to arms, then we will not have a structure to onboard new contributors. We need a plan and a strategy for onboarding

**Comment by Zughy** [comment]
We could ask for UI designers for the main menu and for developers to fix the current [303 bugs](https://github.com/minetest/minetest/issues?q=is%3Aissue+is%3Aopen+label%3ABug) we have. Or, for who wants to start to understand MT, there are ["good first issue" issues](https://github.com/minetest/minetest/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

**Comment by Zughy** [comment]
We could integrate https://github.com/minetest/minetest/issues/14004 here. The blog could have a fixed message (e.g. at the end of the engine section) saying something on the lines of:

---

Wanna contribute and don't know where to start? Try with these simple issues! https://github.com/minetest/minetest/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Wanna help fixing the most annoying bugs for the community? Please do! https://github.com/minetest/minetest/issues?q=is%3Aopen+is%3Aissue+label%3ABug+label%3A%22High+priority%22

(optional?)
Wanna add a feature and you're not sure if it'll be accepted? Have a look at the roadmap <link> or choose one of the "Supported by core dev" label! https://github.com/minetest/minetest/issues?q=is%3Aopen+is%3Aissue+label%3A%22Supported+by+core+dev%22

**Comment by Zughy** [comment]
About art, maybe in the building section:

---

Are you a professional artist or UI designer? We're need you to overhaul our main menu! https://github.com/minetest/minetest/issues/6733

**Comment by MisterE123** [comment]
Do we need more artists/ui designers to design the main menu? I thought we had your design and a few others as well; but lacked the programmer time to implement them, as well as a few engine features...

**Comment by Zughy** [comment]
It wouldn't be bad to have them, my (and Giova's) design wasn't finished anyway

**Comment by erlehmann** [comment]
> I need specifics. If I just put out a general call to arms, then we will not have a structure to onboard new contributors. We need a plan and a strategy for onboarding

I want to point out that It is *already* way too difficult IMO to get regressions fixed or features added.

I do not think that the problem is lack of awareness or lack of interest, but simply that it is too difficult to contribute.

I think that is partially because there are not enough competent reviewers. More contributions mean more work for core devs.

Furthermore, as I pointed out on IRC already, if it was easier to get useful features into the engine, there would be no need for cheat clients – because most of what their authors added to the engine are better CSM support and better debugging features, something vanilla Minetest is lacking. And let's not forget that non-coredev reviews do not ”count” for getting stuff into Minetest.
