### ISSUE TITLE
[Content]: Add an article about  Mineclone's new name

### ISSUE THREAD

**Issue by TheShadowOfHassen** [minetest/blog#150]
I saw this yesterday. I think this is something we should report on: https://www.gamingonlinux.com/2024/04/mineclone2-inspired-by-minecraft-gets-renamed-to-voxelibre/

**Comment by rubenwardy** [comment]
This should be part of a [insert time period here] community update rather than a dedicated blog post

**Comment by TheShadowOfHassen** [comment]
You're right. I just wanted to open an issue so it wouldn't be forgotten.

**Comment by TangentFoxy** [comment]
[The blog post](https://blog.luanti.org/2024/10/13/Introducing-Our-New-Name/) exists now, this issue should be closed.

**Comment by appgurueu** [comment]
> [The blog post](https://blog.luanti.org/2024/10/13/Introducing-Our-New-Name/) exists now, this issue should be closed.

I think you are confused, that blog post was about the Minetest -> Luanti rename, whereas this issue is about the Mineclone -> VoxeLibre rename, and there is no mention of Mineclone or VoxeLibre in the blog post.

That said this issue can be closed as "won't fix" either way because it's been 2/3's of a year now since the rename.

On a positive note, the Mineclone -> VoxeLibre rename got some coverage by Gaming on Linux: https://www.gamingonlinux.com/2024/05/voxelibre-formerly-mineclone2-v0-87-released-moving-away-from-minecraft/.

**Comment by TangentFoxy** [comment]
@appgurueu I am so sorry I misread that.

**Comment by appgurueu** [comment]
> I am so sorry I misread that.

No problem, as said this issue had to be closed either way, just wanted to clear up the confusion (maybe I have mild OCD) :)
