### ISSUE TITLE
[Content] Advtrains Supplemental's news on february

### ISSUE THREAD

**Issue by W3RQ01** [minetest/blog#74]
During the month of february, the Advtrains Supplemental organisation worked on the London S7 mod (https://notabug.org/advtrains_supplemental/tfl_s7_stock_modpack) and added a custom livery function that lets you change the color in certain parts of the body.
It was also notable the merged PR for the NY Subway (https://notabug.org/advtrains_supplemental/advtrains_subway_ny) which received during that month some code additions (like throttle sound) and some tweaks to its texture.
We have mirrored Marnack's new mods (classic coaches and all its ecosystem) and migrated other old/abandoned mods.

**Comment by MisterE123** [comment]
This seems to be a very small update, and I question whether it is blog-worthy. I might have included it anyways if there were good screenshots, but as-is, I cannot see adding it. Also, I attempted to get a screenshot myself, and I was unable to figure out how to set the livery color. I read the readme and saw that I had to use the bike mod, which, is not in the optional_depends. There must be bugs because I think I was able to set the color once, but then unable to set it afterwards. 

The point is that this does not seem blog-worthy at this time.

Thank you for your entry though, please try again when there is a major update.
